version: '2'
services:
  mysql:
    image: 'mysql:8'
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
  php-fpm:
    build: ./deploy/php-fpm
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: '${MYSQL_DATABASE}'
      DB_USERNAME: '${MYSQL_USER}'
      DB_PASSWORD: '${MYSQL_PASSWORD}'
    expose:
      - '9000'
    volumes:
      - '${LARAVEL_DIRECTORY}:/var/www/laravel'
    links:
      - mysql
    working_dir: /var/www/laravel
  nginx:
    image: 'nginx:1'
    depends_on:
      - php-fpm
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    links:
      - php-fpm
    volumes_from:
      - php-fpm
    volumes:
      - './deploy/nginx.conf:/etc/nginx/conf.d/default.conf'
    command: nginx -g 'daemon off;'
